FROM balenalib/%%RESIN_MACHINE_NAME%%-openjdk:latest

COPY /build/libs/piot-server-0.0.1-SNAPSHOT.jar /opt/piot-server-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/opt/piot-server-0.0.1-SNAPSHOT.jar"]