version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mosquitto:/mosquitto/
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"