version: '2'
volumes:
  influxdb-data:
  grafana-data:
services:
  piot-server:
    build: .
    restart: on-failure
    environment:
      - MQTT_URL=tcp://mqtt:1883
      - INFLUXDB_URL=http://influxdb:8086
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - mqtt
      - influxdb

  mqtt:
    image: arm32v6/eclipse-mosquitto
    container_name: mqtt
    restart: on-failure
    expose:
      - 1883
      - 9001
    ports:
      - 1883:1883
      - 9001:9001

  influxdb:
    build: ./influxdb
    container_name: influxdb
    restart: on-failure
    environment:
      - INFLUXDB_DB=piot
      - INFLUXDB_USER=root
      - INFLUXDB_USER_PASSWORD=root
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    build: ./grafana
    restart: on-failure
    ports:
      - 80
    volumes:
      - grafana-data:/data
    environment:
      - GF_SERVER_HTTP_PORT=80
      - GF_PATHS_PROVISIONING=/usr/src/app/provisioning
      - GF_SESSION_PROVIDER=memory
    depends_on:
      - influxdb
