version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mosquitto:/mosquitto/
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
  influxdb:
    image: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=piot
      - INFLUXDB_USER=root
      - INFLUXDB_USER_PASSWORD=root
    ports:
    - 8083:8083
    - 8086:8086
    volumes:
    - ~/influxdb:/var/lib/influxdb